version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: careva-postgres
    restart: always
    environment:
      POSTGRES_USER: careva_user
      POSTGRES_PASSWORD: 999
      POSTGRES_DB: careva
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - careva-network

  redis:
    image: redis:7-alpine
    container_name: careva-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redisdata:/data
    networks:
      - careva-network

volumes:
  pgdata:
  redisdata:

networks:
  careva-network:
    driver: bridge
